user@DESKTOP-G4U9APQ MINGW64 ~/Desktop/project/ai-service (dev/1.4.0)
$ uvicorn app.main:app --reload
INFO:     Will watch for changes in these directories: ['C:\\Users\\user\\Desktop\\project\\ai-service']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [27596] using StatReload
'faiss_index'에서 기존 벡터 저장소를 로드합니다.
Process SpawnProcess-1:
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\user\anaconda3\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\langchain-basic-Ybh8oqrH-py3.12\Lib\site-packages\uvicorn\_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\langchain-basic-Ybh8oqrH-py3.12\Lib\site-packages\uvicorn\server.py", line 66, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\langchain-basic-Ybh8oqrH-py3.12\Lib\site-packages\uvicorn\server.py", line 70, in serve
    await self._serve(sockets)
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\langchain-basic-Ybh8oqrH-py3.12\Lib\site-packages\uvicorn\server.py", line 77, in _serve
    config.load()
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\langchain-basic-Ybh8oqrH-py3.12\Lib\site-packages\uvicorn\config.py", line 435, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\langchain-basic-Ybh8oqrH-py3.12\Lib\site-packages\uvicorn\importer.py", line 22, in import_from_string
    raise exc from None
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\langchain-basic-Ybh8oqrH-py3.12\Lib\site-packages\uvicorn\importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\user\Desktop\project\ai-service\app\main.py", line 5, in <module>
    from .chatbot.router import router as chatbot_router
ModuleNotFoundError: No module named 'app.chatbot.router'
WARNING:  StatReload detected changes in 'app\main.py'. Reloading...
 'faiss_index'에서 기존 벡터 저장소를 로드합니다.
Process SpawnProcess-2:
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\user\anaconda3\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\langchain-basic-Ybh8oqrH-py3.12\Lib\site-packages\uvicorn\_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\langchain-basic-Ybh8oqrH-py3.12\Lib\site-packages\uvicorn\server.py", line 66, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\langchain-basic-Ybh8oqrH-py3.12\Lib\site-packages\uvicorn\server.py", line 70, in serve
    await self._serve(sockets)
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\langchain-basic-Ybh8oqrH-py3.12\Lib\site-packages\uvicorn\server.py", line 77, in _serve
    config.load()
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\langchain-basic-Ybh8oqrH-py3.12\Lib\site-packages\uvicorn\config.py", line 435, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\langchain-basic-Ybh8oqrH-py3.12\Lib\site-packages\uvicorn\importer.py", line 22, in import_from_string
    raise exc from None
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\langchain-basic-Ybh8oqrH-py3.12\Lib\site-packages\uvicorn\importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\user\Desktop\project\ai-service\app\main.py", line 6, in <module>
    from .user_question_chatbot.router import router as user_question_chatbot_router
  File "C:\Users\user\Desktop\project\ai-service\app\user_question_chatbot\router.py", line 7, in <module>
    from .chain import chatbot_chain # 챗봇 체인 임포트
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\project\ai-service\app\user_question_chatbot\chain.py", line 5, in <module>
    from langchain_groq import ChatGroq
ModuleNotFoundError: No module named 'langchain_groq'
